# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12a324bdedc4cd1debbe5dc391af08bdf759c70a0fa18cdc6f5ea62ddf375cb650ad86926dcc652d21daf60a8b89441f89eb47a9479da491f73409291c3cdc54

test:
  secret_key_base: bcf5488f4d359cb1544fdab4b1d6a5194dde3bc40e5669e85df83d651ae9c56e30d82ad3f6309eeb1b6f738bfa027f4b68257b507689eb7da5bd51eb05f5bfc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
